apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pokemon-server-metrics
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: pokemon-server
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
